#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-logkit
Version  : 1.0.1
Release  : 2
URL      : https://github.com/logkit/logkit/archive/1.0.1.tar.gz
Source0  : https://github.com/logkit/logkit/archive/1.0.1.tar.gz
Source1  : https://repo1.maven.org/maven2/logkit/logkit/1.0.1/logkit-1.0.1.jar
Source2  : https://repo1.maven.org/maven2/logkit/logkit/1.0.1/logkit-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: mvn-logkit-data = %{version}-%{release}

%description
# LogKit
[http://www.logkit.info/][website]
LogKit is a logging framework built to be **simple** to get started with, **efficient** to execute, **safe** for shipping code, and **extensible** for flexibility. It is written in pure Swift and is suitable for iOS and OS X application logging. For a developer looking for more power than `println()`, LogKit takes just a moment to get started with, and comes ready to log to the console, a file, an HTTP service, or all three. Need to log to somewhere else? Defining your own Endpoint is easy too.

%package data
Summary: data components for the mvn-logkit package.
Group: Data

%description data
data components for the mvn-logkit package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/logkit/logkit/1.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/logkit/logkit/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/logkit/logkit/1.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/logkit/logkit/1.0.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/logkit/logkit/1.0.1/logkit-1.0.1.jar
/usr/share/java/.m2/repository/logkit/logkit/1.0.1/logkit-1.0.1.pom
